// 마스터 페이지(루트 페이지 = ex. App.jsx)
import Header from '../components/header/header';
import './styles/globals.scss';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap', // 기존 폰트 보이다가 구글폰트로 바꿔치기
});
console.log(roboto);

export const metadata = {
	title: 'Next.js',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Header />
				{/* 구글서버에서 가져온 폰트는 최적화가 되어있지않으므로 network탭에서 확인해보면 똑같은 폰트임에도 불구하고 next 자체적으로 최적화(font optimization)시켜서 가져온 폰트보다 40%정도 파일용량이 더 큼 */}
				<h1 className='roboto'>No Google Font</h1>
				{/* font optimization */}
				<h1 className={roboto.className}>Apply Google Font</h1>
				{children}
			</body>
		</html>
	);
}

/*
  Next에서의 기능별 컴포넌트 구분 

  - Page Component
    : 페이지로 출력될 틀 컴포넌트
    : about/page.jsx, gallery/page.jsx
    : 따로 설정하지 않으면 기본적으로 서버에서 동작돼서 prepage로 사전 랜더링

  - Partial Component
    : 페이지 안쪽에서 호출되면서 부분적인 UI나 기능을 담당하는 컴포넌트 
    : components>header.jsx, components/popup.jsx
*/
